version: "3.9"

services:
  data:
    image: mariadb:latest
    container_name: data
    environment:
      MARIADB_DATABASE: testdb
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - tp3_net

  script:
    build: .
    container_name: script
    volumes:
      - ./app:/app
    networks:
      - tp3_net
    depends_on:
      - data

  http:
    image: nginx:latest
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tp3_net
    depends_on:
      - script

networks:
  tp3_net:
    driver: bridge
